from __future__ import annotations

import difflib
from pathlib import Path

from ..schemas import FixAgentResult, GraphState, Status


def run_fix_agent(state: GraphState) -> GraphState:
    result = apply_deterministic_fix(state)
    return {**state, "fix_result": result.to_dict()}


def apply_deterministic_fix(state: GraphState) -> FixAgentResult:
    workspace_value = state.get("test_result", {}).get("workspace_dir", "")
    workspace = Path(workspace_value) if workspace_value else None
    if workspace is None or not workspace.is_dir():
        return FixAgentResult(
            agent="FixAgent",
            status=Status.FAILED,
            warnings=["TestAgent workspace is missing; no source file was modified."],
        )

    failures = state.get("test_result", {}).get("test_results", [])
    evidence = "\n".join(
        str(failure.get("message", "")) + "\n" + str(failure.get("traceback", ""))
        for summary in failures
        for failure in summary.get("failures", [])
    )
    assertion_matches = "AssertionError: -1 != 3" in evidence or "assert -1 == 3" in evidence
    target = workspace / "main.py"
    if not assertion_matches or not target.is_file():
        return FixAgentResult(
            agent="FixAgent",
            status=Status.SKIPPED,
            warnings=["No supported deterministic fix matched the current failure."],
        )

    before = target.read_text(encoding="utf-8")
    if "return a - b" not in before:
        return FixAgentResult(
            agent="FixAgent",
            status=Status.SKIPPED,
            warnings=["main.py does not contain the supported demo bug."],
        )
    after = before.replace("return a - b", "return a + b", 1)
    target.write_text(after, encoding="utf-8")
    # The demo replacement has the same byte length and can happen within one
    # filesystem timestamp tick. Remove only generated bytecode for this module
    # so the verification process cannot reuse the pre-fix implementation.
    for cached in (workspace / "__pycache__").glob("main.*.pyc"):
        cached.unlink()
    patch = "".join(
        difflib.unified_diff(
            before.splitlines(keepends=True),
            after.splitlines(keepends=True),
            fromfile="a/main.py",
            tofile="b/main.py",
        )
    )
    issue_ids = [str(issue.get("issue_id")) for issue in state.get("report_result", {}).get("issues", [])]
    return FixAgentResult(
        agent="FixAgent",
        status=Status.COMPLETED,
        fixed_issue_ids=issue_ids,
        modified_files=["main.py"],
        patches=[patch],
    )
